#!/bin/bash
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'BD-P01 – Monitorar performance dos servidores de BD produção' --parent-name 'Requisição::Banco de Dados::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'BD-P02 – Monitorar realização do Backup de BD full no ambiente de produção' --parent-name 'Requisição::Banco de Dados::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'BD-P03 - Monitorar crescimento das bases de dados  arquivos mdf e transaction og   de Producao' --parent-name 'Requisição::Banco de Dados::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'BD-P04 - Monitorar fragmentação de índice das bases de dados' --parent-name 'Requisição::Banco de Dados::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'NET-P01 Verificação dos logs do Nagios e do NetSight nas últimas 24 horas' --parent-name 'Requisição::Redes::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'NET-P02 Monitoramento backup configuração dos equipamentos  Backup NetSight  -Monitoramento' --parent-name 'Requisição::Redes::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'NET-P03 Checar list Ativos de Rede dos Data Centers Xerém e RC' --parent-name 'Requisição::Redes::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'NET-P04 Avaliação de performance dos links de comunicação' --parent-name 'Requisição::Redes::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'NET-P05 - Medir desempenho do link Xerém - RC e RC- Internet' --parent-name 'Requisição::Redes::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'NET-P06 - Gerar relatório diário de falhas apresentadas no monitoramento e gerar relatório histórico para ser entregue junto ao relatório mensal' --parent-name 'Requisição::Redes::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'NET-P07 - Backup e check de alteração na configuração' --parent-name 'Requisição::Redes::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'NET-P08 - Análise de desempenho dos equipamentos DELL SAN' --parent-name 'Requisição::Redes::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'NET-P09 - Análise de desempenho dos equipamentos Switch Core' --parent-name 'Requisição::Redes::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'NET-P10 - Análise de desempenho dos equipamentos  Swiches Topo de Rack' --parent-name 'Requisição::Redes::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'SRV-P01 – CHEQUE DATA CENTER – MONITORAMENTO  ' --parent-name 'Requisição::Servidores::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'SRV-P02 – COMMCELL COMMVAULT - Checar Backup Commvault' --parent-name 'Requisição::Servidores::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --nwqPanrcbhkl18sNXccvVame 'SRV-P03 – STORAGE NETAPP - Checar Storage - RC e Xerém' --parent-name 'Requisição::Servidores::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'SRV-P04 – GERADOR RC - Realizar Teste do Gerador do RC' --parent-name 'Requisição::Servidores::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'SRV-P05 – SERVIDORES EXCHANGE - Checar e Verificar Disponibilidade Exchange' --parent-name 'Requisição::Servidores::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'SRV-P06 – AD - Checar e Verificar Disponibilidade Active Directory' --parent-name 'Requisição::Servidores::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'SEG-P01 - Execução das Rotinas de análise do Firewall' --parent-name 'Requisição::Segurança::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'SEG-P02 - Avaliar o comportamento e manutenção dos Ips permanecidos na Blacklist por mais de 30 dias' --parent-name 'Requisição::Segurança::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'SEG-P03 - Avaliar as estações com problemas relacionados a instalação do EPP' --parent-name 'Requisição::Segurança::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'SEG-P04 - Identificar as estações que necessitam de atualização dos Sistemas Operacionais' --parent-name 'Requisição::Segurança::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'SEG-P05 - Realizar teste dos firewalls dos Datacenters' --parent-name 'Requisição::Segurança::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'SEG-P06 - Identificar contas com privilégios administrativos, avaliar a pertinência e tratar as correções' --parent-name 'Requisição::Segurança::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'SRVRS-P01  diária  - Checar todos os servidores, performance, espaço em disco e máquinas virtuais' --parent-name 'Requisição::Servidores RS::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'SRVRS-P02  diária  - Checar o Storage' --parent-name 'Requisição::Servidores RS::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'SRVRS-P03  diária  - Checar o backup' --parent-name 'Requisição::Servidores RS::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'SRVRS-P04  diária  - Checar a temperatura do DC' --parent-name 'Requisição::Servidores RS::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'NETRS-P01  diária  - Checagem dos Ativos' --parent-name 'Requisição::Redes RS::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'NETRS-P02  diária  - Testar link com RNP, Testar link com Internet, Regional Pelotas, Regional Santa Maria, Regional Santo Ângelo, Regional Caxias do Sul, Regional Passo Fundo, Sede' --parent-name 'Requisição::Redes RS::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'NETRS-P03  diária  - Monitorar Carga-Temperatura-Utilização dos nobreaks, Serviços DHCP-DNS-PROXY-FIREWALL-VPN' --parent-name 'Requisição::Redes RS::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'NETRS-P04  mensal  - Verificar-Validar-Testar' --parent-name 'Requisição::Redes RS::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'NETRS-P05  trimestral  - Testar No-Break-Gerador' --parent-name 'Requisição::Redes RS::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
su -c "/opt/otrs/bin/otrs.Console.pl Admin::Service::Add --name 'RVRS-P05  diária  - Checar o serviço e o servidor de impressão' --parent-name 'Requisição::Atendimento::Rotineira' --type 'End User Service' --criticality '3 normal'" -s /bin/bash otrs
